
@ECHO This file will call up subsonic subcommander, automatically load up the VRM.Subsonic2 config file and generate all the files to auto-generate folder.

del "CoffeeShop.Core\AutoGenerated\*"
SubCommander\sonic generate /config "CoffeeShop\App.config" /out "CoffeeShop.Core\AutoGenerated"